version: '3'

services:
  ros2-mission:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2-mission
    environment:
      - ROS_DOMAIN_ID=69
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/fastrtps_profile.xml
      - VNC_PASSWD=none
      - QT_QPA_PLATFORM=vnc
    volumes:
      - ./ros2_ws:/ros2_ws
    # Replace host networking with bridge mode and explicit port mappings
    expose:
      - "5900:5900"  # VNC port
      - "5901:5901" 
    ports: # Additional VNC port
      # ROS2/DDS discovery and communication ports
      - "7400-7500:7400-7500/udp"
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: ["/start_vnc.sh"]
